version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - server
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    environment:
      - REDIS_ARGS=--requirepass $REDIS_PASSWORD
    networks:
      - server
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: $MODE
    privileged: true
    restart: always
    env_file:
      - .env
    environment:
      - MYSQLDB_HOST=$DB_HOST
      - MYSQLDB_PORT=$DB_DOCKER_PORT
      - MYSQLDB_DATABASE=$DB_NAME
      - MYSQLDB_USER=root
      - MYSQLDB_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - $CLIENT_APP_LOCAL_PORT:5173
      - $SERVER_APP_LOCAL_PORT:2022
      - 80:80
      - 443:443
      - 2222:22
    volumes:
      # - .:/app
      - ./apps/client/src:/app/apps/client/src
      - /app/node_modules
      - ./.home:/home
      - ./.data:/data
      - ./user_skel:/etc/skel
    networks:
      - server
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:

networks:
  server:
    driver: bridge
